### ISSUE TITLE
Will this gem be passed to new maintainer? 

### ISSUE THREAD

**Issue by skatkov** [leejarvis/gridhook#10]
Seems like a lot of people have already worked on different additions to this gem. It would be really useful at least to keep this up to date. Any chances your planning to find new maintainers for this gem?

**Comment by leejarvis** [comment]
@skatkov I'm open to additional contributors. I don't have any plans to work on this in the near future, but it's always possible that I'll start using it at work again at some point. Would you like to help maintain it?

**Comment by skatkov** [comment]
@leejarvis thanks for an offer. I hardly work nowadays (15 hours a week), so i have some spare time to waste. :)

I'm testing out this gem with one of my customers projects and considering it in couple of other projects. I think I'll be interested in longevity of this gem and would contribute towards this goal. I'll try to come back to you with some pull requests. (and maybe some proposals).

**Comment by skatkov** [comment]
@leejarvis Is it possible to hook-up travisci to this repository?

**Comment by leejarvis** [comment]
@skatkov Great, good to know. I've added Travis support (the build looks like it's currently failing). Thanks for the offer of sending some PRs!
